import type { NextPage } from 'next'
import Head from 'next/head'
import { useRef, useState } from 'react'
import { DaumSearch } from 'src/components/daum'
import { GoogleSearch } from 'src/components/google'
import { NaverSearch } from 'src/components/naver'
import { StackoverflowSearch } from 'src/components/stackoverflow'
import { YoutubeSearch } from 'src/components/youtube'

const Home: NextPage = () => {
  const [search, setSearch] = useState<string>()
  const [platforms, setPlatforms] = useState<Set<string>>(new Set())
  const searchInputRef = useRef<HTMLInputElement>(null)
  const platformCheckboxRef = useRef<HTMLFieldSetElement>(null)

  return (
    <div>
      <Head>
        <title>Project SE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input ref={searchInputRef} />
        <button
          onClick={() => {
            if (!searchInputRef.current?.value) return
            const platforms = new Set<string>()
            for (
              let i = 0;
              i < (platformCheckboxRef.current?.elements.length || 0);
              i++
            ) {
              const checkbox = platformCheckboxRef.current?.elements.item(
                i
              ) as HTMLInputElement
              if (checkbox.checked) platforms.add(checkbox.name)
            }
            setPlatforms(platforms)
            setSearch(searchInputRef.current.value)
          }}
        >
          Search
        </button>
        <fieldset ref={platformCheckboxRef}>
          <label>
            <input name="goolge" type="checkbox" />
            Google
          </label>
          <label>
            <input name="youtube" type="checkbox" />
            Youtube
          </label>
          <label>
            <input name="daum" type="checkbox" />
            Daum
          </label>
        </fieldset>
        <div>
          {platforms.has('goolge') && <GoogleSearch search={search} />}
          {/* {search && <NaverSearch search={search} />} */}
          {platforms.has('youtube') && <YoutubeSearch search={search} />}
          {platforms.has('daum') && <DaumSearch search={search} />}
          {/* {search && <StackoverflowSearch search={search} />} */}
        </div>
      </main>
    </div>
  )
}

export default Home
